-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0uRYbofYYmEBAbTA
8zgXZE3V8Vfor7nurfo/FNnxkVSgCgYIKoZIzj0DAQehRANCAATgNfueTlvWufZi
v8yLEm996XH9kh7lGaZS/RvT7LKh3tZykuHz2OGfRTecMaboEAwLfKBLjCrHFKiZ
iX7a5u2/
-----END PRIVATE KEY-----