export default {
  PROFILESCREEN: 'ProfileScreen',
  CHATSCREEN: 'ChatScreen',
  CHATSCREEN2: 'ChatScreen2',
  MESSAGESCREEN: 'MessageScreen',
  // SPLASHSCREEN: 'SplashScreen',
  ENABLENOTIFY: 'EnableNotify',
  CREATEPROFILE: 'CreateProfile',
  SELECTGENDER: 'SelectGender',
  SELECTLOCATION: 'SelectLocation',
  SETTINGSCREEN: 'SettingScreen',
  LASTCALLMODAL: 'LastCallScreen',
  OTPSCREEN: 'OtpScreen',
  onBoardingScreen: 'OnBoarding Screen',
  MATCHSCREEN: 'MatchScreen',
  TABROUTES: 'TabRoutes',
  DrawerStack: 'Drawer Stack',
  HOME: 'Home',
  ENCOUNTER_HOME: 'EnCounter Home',
  ONBOARDING_SCREEN: 'On Boarding Screen',
  ADDMEDIASCREEN: 'AddMediaScreen',
  VOICE_DROP: 'VoiceDrop',
  EDITPROFILE: 'EditProfile',
  VIEWPROFILE: 'View Profile',
  LOGINSCREEN: 'Login Screen',
  FORGOT_PASSWORD: 'ForgotPassword',
  CREATE_PASSWORD: 'CreatePassword',
  SELECT_USER_TYPE: 'SelectUserType',
  SET_PREFERENCES_AUTH: 'SetPreferencesAuth',
  SETUP_COMPLETED: 'SetupCompleted',
  PROFILE_VERIFICATION: 'ProfileVerification',
  WELCOME_SCREEN: 'WelcomeScreen',
  AUTH_SCREENS: 'AuthScreens',
  SUBSCRIPTION_SCREEN: 'SubscriptionScreen',
  ALL_GALLERY_IMAGES: 'AllGalleryImages',
  ALL_PRIVATE_GALLERY_IMAGES: 'AllPrivateGalleryImages',
  CHANGE_PASSWORD: 'ChangePassword',
  TERMS_CONDITION_PRIVACY_POLICY: 'TermsConditionPrivacyPolicy',
  BONKS_HOME: 'BonksHome',
  FACE_DETECTION: 'FaceDetection',
  BLOCKED_USERS: 'BlockedUsers',
  MY_BONK_FAVOURITES: 'MyBonkFavourites',
  VIDEO_SESSION: 'VideoSession',
  BONKS_MESSAGES: 'BonksMessages',
  SELECT_TAGS: 'SelectTags',
  ANIMATED_SPLASH_SCREEN: 'AnimatedSplashScreen',
  APP_PIN_LOCK: 'AppPinLock',
  WALK_SAFE_MAP_SCREEN: 'WalkSafeMapScreen',
  JOURNEY_SCREEN: 'JourneyScreen',
  CONGRATS_SCREEN: 'CongratsScreen',
  WALKSAFE_INTRO: 'WalkSafeIntroScreen',
  FORGOT_SCREEN: 'ForgotScreen',
  SHOW_USER_DETAILS: 'ShowUserDetails',
  FACE_DETECTION_EDIT: 'FaceDetectionEdit',
  ADDITIONAL_DETAILS: 'AdditionalDetails',
  PREFERENCES_SCREEN: 'PreferencesScreen',
  CONTACT_US: 'ContactScreen',
  FORGOT_USERNAME: 'ForgotUsername',
  SIGNUP: 'Signup',
  GROUP_LIVE_SCREEN: 'Group Live Screen',
  PULBLIC_CHAT_ROOM: 'PublicChatRoom',
  FAV: 'Fav',
  EXPLORE: 'Explore',
  VIEWED_ME_LIST: 'ViewedMeLists',
  STRIPE_PAYMENT: 'StripePayment',
  CREATE_CHAT_ROOM: 'CreateChatRoom',
  ADD_CHAT_MEMBER: 'Add Chat Member',
  PUBLIC_GROUP_CHAT: 'PublicGroupChat',
  PRIVATE_GROUP_CHAT: 'PrivateGroupChat',
  View_Member_Group: 'ViewMemberGroup',
  BOOM_ME: 'Boom Me',
  ONE_TIME_READ: 'OneTimeRead',
  MAP_SCREEN: 'MapScreen',
  SET_PIN_SCREEN: 'SetPinScreen',
  VERIFY_PROFILE_PIN_SCREEN: 'VerifyProfilePINScreen',
  BOTTOM_STACK: 'BottomStack',
  PROFILE_PERMISSIONS: 'ProfilePermissions',
  FAVORITE_CHAT: 'FavoriteChat',
  ADMIN_CONTACT: 'AdminContact',
  TAPS_HISTORY: 'TapsHistory',
  CYPHER_SCREEN: 'CypherScreen',
};
