# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers =>true
pod 'FirebaseCore', :modular_headers =>true
pod 'FirebaseInstallations', :modular_headers =>true
pod 'FirebaseCoreExtension', :modular_headers =>true
pod 'GoogleDataTransport', :modular_headers =>true
pod 'nanopb', :modular_headers =>true
pod 'leveldb-library', :modular_headers =>true
pod 'FirebaseAppCheckInterop', :modular_headers =>true
pod 'SDWebImage', :modular_headers => true

# 🛠️ Force ZegoExpressEngine version to match react-native-zego-express-engine
# pod 'ZegoExpressEngine', '3.20.2'

setup_permissions([
  'Camera',
  'PhotoLibrary',
  'LocationAlways',
  'LocationWhenInUse'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path

target 'RN_Encountr' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
        # Patch fmt/base.h to fix modern Xcode compilation errors
    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      puts "Patching #{fmt_base} to disable consteval support..."
      content = File.read(fmt_base)
      patched_content = content.gsub(/#\s*define\s+FMT_USE_CONSTEVAL\s+1/, '#  define FMT_USE_CONSTEVAL 0')
      if content != patched_content
        File.open(fmt_base, "w") { |file| file.puts patched_content }
      end
    end
  end
end
